/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import connection.ConnectionFactory;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Produto;
import model.dao.ProdutoDAO;

/**
 *
 * @author Pretinho
 */
public final class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
//        O código abaixo troca o icone do JFrame e já foi testado no momento usei a configuração de propriedades
//        do jFrame no NetBeans para resolver o problema. 

//        URL caminhoIcone = getClass().getResource("/imagens/rolo-de-filme.png");
//        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
//        this.setIconImage(iconeTitulo);

        Connection con = ConnectionFactory.getConnection();
        
        if (con != null) {
            lblConPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("../imagens/conection-ok.png")));
            
        } else {
            lblConPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("../imagens/No-conection.png")));
            
        }
        
        
//  Chamada da classe responsável pelo controle da jTableModel
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        jTProdutos.setRowSorter(new TableRowSorter(modelo));

        readPrincipal();
        
    }
    public void readPrincipal(){
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        pdao.read().forEach((p) -> {
            modelo.addRow(new Object[]{
                p.getId_dvd(),
                p.getDvd_titulo(),
                p.getDvd_genero(),
                p.getDvd_classificacao(),
                p.getDvd_sinopse(),
                p.getDvd_imagem()
            });
        });
 
    }
    
    
        public void readForTytle(String titulo){
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        pdao.readForTytle(titulo).forEach((p) -> {
          
            modelo.addRow(new Object[]{
                p.getId_dvd(),
                p.getDvd_titulo(),
                p.getDvd_genero(),
                p.getDvd_classificacao(),
                p.getDvd_sinopse(),
                p.getDvd_imagem()
            });
        });
 
    }
        
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblClassificacao = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblSinopse = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        lblGenero = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextSinopse = new javax.swing.JTextArea();
        cbClassificacao = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        jPanel4Imagem = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblNomeImagem = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblConPrincipal = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de DVD´s");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/dvd-rolo.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblClassificacao.setText("Classificação");

        txtTitulo.setEnabled(false);
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTituloKeyPressed(evt);
            }
        });

        lblSinopse.setText("Sinópse");

        btnExcluir.setBackground(new java.awt.Color(51, 51, 255));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_delete.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(51, 51, 255));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_form_edit.png"))); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.setEnabled(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblGenero.setText("Gênero");

        lblTitulo.setText("Título");

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma das opções", "AÇÃO", "FICÇÃO", "DRAMA", "ROMÂNTICO", "GERRA", "COMÉDIA ROMÂNTICA", "COMÉDIA", "TERROR", "SUSPENSE", "SHOW", "MUSICAL", "AUTO-AJUDA", "GOSPEL", "OUTROS" }));
        cbGenero.setEnabled(false);
        cbGenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbGeneroKeyPressed(evt);
            }
        });

        jTextSinopse.setColumns(20);
        jTextSinopse.setRows(5);
        jTextSinopse.setEnabled(false);
        jScrollPane1.setViewportView(jTextSinopse);

        cbClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma das opções", "EXCELENTE", "ÓTIMO", "MUITO BOM", "BOM", "RUIM", "MUITO RUIM", " " }));
        cbClassificacao.setEnabled(false);
        cbClassificacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbClassificacaoKeyPressed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(51, 51, 255));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_add.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Render DVD.png"))); // NOI18N
        lblImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4ImagemLayout = new javax.swing.GroupLayout(jPanel4Imagem);
        jPanel4Imagem.setLayout(jPanel4ImagemLayout);
        jPanel4ImagemLayout.setHorizontalGroup(
            jPanel4ImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4ImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4ImagemLayout.setVerticalGroup(
            jPanel4ImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4ImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Foto");

        btnNovo.setBackground(new java.awt.Color(51, 51, 255));
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book_go.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(51, 51, 255));
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_redo.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome:");

        btnBusca.setBackground(new java.awt.Color(51, 51, 255));
        btnBusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBusca.setForeground(new java.awt.Color(255, 255, 255));
        btnBusca.setText("CONSULTA");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 0, 51));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_redo.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 83, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198)
                                .addComponent(jLabel2)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblNomeImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBusca)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGenero)
                        .addGap(10, 10, 10)
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblClassificacao)
                        .addGap(6, 6, 6)
                        .addComponent(cbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblSinopse)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(lblNomeImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4Imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblData.setForeground(new java.awt.Color(0, 0, 204));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        lblData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblHora.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 0, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setBorder(javax.swing.BorderFactory.createTitledBorder("Hora"));
        lblHora.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TÍTULO", "GÊNERO", "CLASSIFC.", "SINÓPSE", "IMAGEM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutosMouseClicked(evt);
            }
        });
        jTProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTProdutosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTProdutos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblConPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblConPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        setSize(new java.awt.Dimension(1197, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
            
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();

            p.setId_dvd((int)jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 0));

            dao.delete(p);
            readPrincipal();
            
//Reinicia os campos
//    Limpa campos
            txtTitulo.setText("");
            cbGenero.setSelectedIndex(0);
            cbClassificacao.setSelectedIndex(0);
            jTextSinopse.setText("");
            lblNomeImagem.setText(null);
            lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("../imagens/Render DVD.png")));
            
//    Desabilita os campos            
            txtTitulo.setEnabled(false);
            cbGenero.setEnabled(false);
            cbClassificacao.setEnabled(false);
            jTextSinopse.setEnabled(false);
            
//    Desabilita os botões
            btnExcluir.setEnabled(false);
            btnAtualizar.setEnabled(false);
            btnLimpar.setEnabled(false);
            btnSalvar.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
              
              Produto p = new Produto();
              ProdutoDAO dao = new ProdutoDAO();

              p.setDvd_titulo(txtTitulo.getText().toUpperCase());
              p.setDvd_genero((String) cbGenero.getSelectedItem());
              p.setDvd_classificacao((String)cbClassificacao.getSelectedItem());
              p.setDvd_sinopse(jTextSinopse.getText());
              p.setId_dvd((int)jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 0));
              p.setDvd_imagem(lblNomeImagem.getText());
              
              dao.update(p);
              readPrincipal();
              
//Reinicia os campos e botões
//    Limpa campos
            txtTitulo.setText("");
            cbGenero.setSelectedIndex(0);
            cbClassificacao.setSelectedIndex(0);
            jTextSinopse.setText("");
            lblNomeImagem.setText(null);
            lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("../imagens/Render DVD.png")));
            
//    Desabilita os campos            
            txtTitulo.setEnabled(false);
            cbGenero.setEnabled(false);
            cbClassificacao.setEnabled(false);
            jTextSinopse.setEnabled(false);
            
//    Desabilita os botões
            btnExcluir.setEnabled(false);
            btnAtualizar.setEnabled(false);
            btnLimpar.setEnabled(false);
            btnSalvar.setEnabled(false);
              
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jTProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutosMouseClicked
            
// Executa a leitura da posição clicada e preenche os campos com os dados do registro            
            txtTitulo.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 1).toString());
            cbGenero.setSelectedItem(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 2).toString());
            cbClassificacao.setSelectedItem(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 3).toString());
            jTextSinopse.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 4).toString());
            lblNomeImagem.setText((String) jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 5).toString());
            
//            
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();
            
            p.setDvd_imagem((String)jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 5));
            String nomeImagem = p.getDvd_imagem();


            
                if (!nomeImagem.isEmpty()){
                    
                    ImageIcon icone = new ImageIcon("C:\\Users\\Pretinho\\Pictures\\dvdImagens\\" + nomeImagem);
                    lblImagem.setIcon(icone);
                    lblNomeImagem.setText(nomeImagem);
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Não existe Imagem para este registro");
                }
            
//Reinicia campos e botões
//  Habilita os campos
      txtTitulo.setEnabled(true);
      cbGenero.setEnabled(true);
      cbClassificacao.setEnabled(true);
      jTextSinopse.setEnabled(true);
      
//  Prepara botões    
      btnLimpar.setEnabled(false);
      btnExcluir.setEnabled(true);
      btnAtualizar.setEnabled(true);
      btnNovo.setEnabled(true);
      btnSalvar.setEnabled(false);
      
//  posicion o cursor
      txtTitulo.requestFocus();
    }//GEN-LAST:event_jTProdutosMouseClicked

    private void jTProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProdutosKeyReleased
            
// Executa a leitura da posição escolhida com a seta e preenche os campos com os dados do registro            
            txtTitulo.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 1).toString());
            cbGenero.setSelectedItem(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 2).toString());
            cbClassificacao.setSelectedItem(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 3).toString());
            jTextSinopse.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 4).toString());
            lblNomeImagem.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 5).toString());
            
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();
            
            p.setDvd_imagem((String)jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 5));
            String nomeImagem = p.getDvd_imagem();


            
                if (!nomeImagem.isEmpty()){
                    
                    ImageIcon icone = new ImageIcon("C:\\Users\\Pretinho\\Pictures\\dvdImagens\\" + nomeImagem);
                    lblImagem.setIcon(icone);
                    lblNomeImagem.setText(nomeImagem);
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Não existe Imagem para este registro");
                }


//Reinicia campos e botões
//  Habilita os campos
      txtTitulo.setEnabled(true);
      cbGenero.setEnabled(true);
      cbClassificacao.setEnabled(true);
      jTextSinopse.setEnabled(true);
      
//  Prepara botões    
      btnLimpar.setEnabled(false);
      btnExcluir.setEnabled(true);
      btnAtualizar.setEnabled(true);
      btnNovo.setEnabled(true);
      btnSalvar.setEnabled(false);
      
//  posicion o cursor
      txtTitulo.requestFocus();
    }//GEN-LAST:event_jTProdutosKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
    //Não permite cadastrar registro com campo Título vazio 
        if(txtTitulo.getText(). equals("")){
            txtTitulo.requestFocus();
            JOptionPane.showMessageDialog(null, "O campo Título é obrigatório.","AVISO",JOptionPane.WARNING_MESSAGE);
        return;
        }
        if(lblNomeImagem.getText(). equals("")){
                txtTitulo.requestFocus();
                JOptionPane.showMessageDialog(null, "A escolha da imagem é obrigatória! Click duas vezes no campo da imagem para selecionar.","AVISO",JOptionPane.WARNING_MESSAGE);
        return;
    }
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        
            p.setDvd_titulo(txtTitulo.getText().toUpperCase());
            p.setDvd_genero((String) cbGenero.getSelectedItem());
            p.setDvd_classificacao((String)cbClassificacao.getSelectedItem());
            p.setDvd_sinopse(jTextSinopse.getText());
            p.setDvd_imagem(lblNomeImagem.getText());
            
//          Cria novo registro
            dao.create(p);
            readPrincipal();
            
            
//  Reinicia campos e botões
//      Limpa os campos desabilita campos
            txtTitulo.setText("");
            cbGenero.setSelectedIndex(0);
            cbClassificacao.setSelectedIndex(0);
            jTextSinopse.setText("");
            lblNomeImagem.setText("");
            lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("../imagens/Render DVD.png")));
            txtTitulo.setEnabled(false);
            cbGenero.setEnabled(false);
            cbClassificacao.setEnabled(false);
            jTextSinopse.setEnabled(false);
            
//      Prepara os botões            
            btnNovo.setEnabled(true);
            btnAtualizar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnLimpar.setEnabled(false);
            btnSalvar.setEnabled(false);
            
            
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtTituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyPressed
//  Faz o cursor mudar de campo quando Enter é precionado
        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
           cbGenero.requestFocus();
       }
    }//GEN-LAST:event_txtTituloKeyPressed

    private void cbGeneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbGeneroKeyPressed
//  Faz o cursor mudar de campo quando Enter é precionado 
        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
           cbClassificacao.requestFocus();
       } 
    }//GEN-LAST:event_cbGeneroKeyPressed

    private void cbClassificacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbClassificacaoKeyPressed
//  Faz o cursor mudar de campo quando Enter é precionado
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextSinopse.requestFocus();
        }
    }//GEN-LAST:event_cbClassificacaoKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Data no rodapé
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        lblData.setText(formato.format(dataSistema));
        
        // Hora no rodapé
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void lblImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseClicked
        // TODO add your handling code here:
        
         if(evt.getClickCount() == 2 && (!txtTitulo.getText().isEmpty())){
             JFileChooser fc = new JFileChooser();
             fc.setDialogTitle("Procurar arquivos");
             fc.setCurrentDirectory(new File("C:\\Users\\Pretinho\\Pictures"));
             fc.setFileFilter(new FileFilter() {
                 
                 @Override
                 public boolean accept(File file) {
                     String name = file.getAbsolutePath();
                     return name.endsWith("jpg") | name.endsWith("png") | name.endsWith("bmp") | file.isDirectory();
                     
                 }

                 @Override
                 public String getDescription() {
                     return "Filtro(jpg,png,bmp e Diretórios)";
                 }
             });
             
             if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
                 
                String path = fc.getSelectedFile().getAbsolutePath();
                ImageIcon icone1 = new ImageIcon(path);
                Image img = icone1.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), Image.SCALE_DEFAULT);
                lblImagem.setIcon(new ImageIcon(img));
                String nomeImagem = System.currentTimeMillis() + ".jpg";
                lblNomeImagem.setText(nomeImagem);
                
                
                File novaImagem = new File("C:\\Users\\Pretinho\\Pictures\\dvdImagens\\" + nomeImagem);
                
                BufferedImage bi = new BufferedImage(lblImagem.getWidth(), lblImagem.getHeight(), BufferedImage.TYPE_INT_RGB);
                Graphics2D g2d = bi.createGraphics();
                g2d.drawImage(img, null, null);
                g2d.dispose();
                 try {
                     ImageIO.write(bi, "JPG", novaImagem);
                 } catch (IOException ex) {
                     JOptionPane.showMessageDialog(null, "Falha na criação, dimensionamento ou gravação do arquivo imagem");
                 }
                 
             } else{
                 JOptionPane.showMessageDialog(null, "Selecione um arquivo de imagem válido");
                 
             }
             
             
         }    
        
        
        
    }//GEN-LAST:event_lblImagemMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
//Prepara campos e botões
//  Habilita os campos e posiciona o cursor
        txtTitulo.setEnabled(true);
        cbGenero.setEnabled(true);
        cbClassificacao.setEnabled(true);
        jTextSinopse.setEnabled(true);
        txtTitulo.requestFocus();
        
//  Limpa os campos 
        txtTitulo.setText("");
        cbGenero.setSelectedIndex(0);
        cbClassificacao.setSelectedIndex(0);
        jTextSinopse.setText("");
        lblNomeImagem.setText("");
        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("../imagens/Render DVD.png")));
        
        
//  Normaliza os botões        
        btnAtualizar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnLimpar.setEnabled(true);
        btnSalvar.setEnabled(true);
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
//Limpa todos os campos e posiciona o cursor        
      txtTitulo.setText("");
      cbGenero.setSelectedIndex(0);
      cbClassificacao.setSelectedIndex(0);
      jTextSinopse.setText("");
      lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("../imagens/Render DVD.png")));
      lblNomeImagem.setText("");
      txtTitulo.requestFocus();
      
      
              
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
        
        readForTytle(txtConsulta.getText());
        
        
        
        
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        /*</editor-fold>

//        </editor-fold>
//        </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbClassificacao;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4Imagem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JTextArea jTextSinopse;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblConPrincipal;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNomeImagem;
    private javax.swing.JLabel lblSinopse;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener {
@Override
public void actionPerformed(ActionEvent e) {
Calendar now = Calendar.getInstance();
lblHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
}
}
    
    
    
}//Fim da classe principal
